Repository DO-youhave/Frontend, pull requests merged in 2023-02, with the labels that each got.

#12 feat: header 프레임 생성
  src/App.tsx
  src/components/Header.tsx
Labels: enhancement

#13 style: notosanskr 글로벌스타일 지정
  index.html
  src/styles/GlobalStyle.tsx
Labels: style

#14 feat: 골목길 카테고리 / 마이페이지 프레임 생성
  public/profile.svg
  src/App.tsx
  src/components/Category.tsx
  src/components/MyInfo/Menus.tsx
  src/components/MyInfo/Profile.tsx
  src/constants/colors.ts
  src/constants/routes.ts
  src/layouts/MyInfo.tsx
  src/styles/GlobalStyle.tsx
  src/utils/currentPath.ts
Labels: enhancement

#15 fix: 전단지 골목 경로 수정
  src/App.tsx
  src/components/Category.tsx
  src/constants/routes.ts
  src/utils/currentPath.ts
Labels: bug

#16 feat: 검색 기능 제작
  public/img/profile.svg
  public/img/search.svg
  src/App.tsx
  src/components/.empty
  src/components/Category.tsx
  src/components/Header.tsx
  src/components/MyInfo/Profile.tsx
  src/components/PopularTags.tsx
  src/components/Search.tsx
  src/hooks/.empty
  src/hooks/useSearch.ts
  src/pages/FlyerStreet.tsx
  src/pages/Home.tsx
  tsconfig.json
  vite.config.ts
Labels: enhancement

#17 refactor: 네비게이트 URL 하드코딩 변경
  src/App.tsx
  src/components/Category.tsx
  src/components/Header.tsx
  src/components/Search.tsx
  src/constants/routes.ts
  src/hooks/useSearch.ts
Labels: refactor

#18 feat: 전단지 리스트 제작(+ 메뉴 카테고리 주소 파라미터 수정)
  src/components/Header.tsx
  src/components/Street/Category.tsx
  src/components/Street/FlyerList.tsx
  src/components/Street/PopularTags.tsx
  src/components/Street/Search.tsx
  src/components/Street/Sort.tsx
  src/constants/colors.ts
  src/constants/routes.ts
  src/hooks/getParams.ts
  src/hooks/useSearch.ts
  src/pages/FlyerStreet.tsx
Labels: enhancement, refactor

#23 style: 골목길 페이지 width 수정
  public/img/flyerBg.png
  src/components/Header.tsx
  src/components/Street/Category.tsx
  src/components/Street/FlyerList.tsx
  src/components/Street/PopularTags.tsx
  src/components/Street/Search.tsx
  src/pages/FlyerStreet.tsx
Labels: style

#24 feat: 전단지 작성 페이지 퍼블리싱 작업
  public/img/back.png
  public/img/close.png
  src/App.tsx
  src/components/Header.tsx
  src/components/Street/Category.tsx
  src/constants/categorys.ts
  src/layouts/HeaderOff.tsx
  src/layouts/HeaderOn.tsx
  src/pages/MakeFlyer.tsx
Labels: enhancement

#25 feat: 마이페이지 최근알림 탭 생성 및 전단지 상세 페이지 기초
  public/img/dots.svg
  public/img/tape.svg
  src/App.tsx
  src/components/MyInfo/Menus.tsx
  src/components/MyInfo/Recent.tsx
  src/components/Street/Category.tsx
  src/components/Street/Search.tsx
  src/components/Street/Sort.tsx
  src/hooks/getParams.ts
  src/hooks/useGetParams.ts
  src/hooks/useSearch.ts
  src/pages/FlyerDetail.tsx
  src/pages/MyInfo.tsx
Labels: enhancement, refactor

#26 refactor: 전단지 제작 페이지 관심사 분리
  package-lock.json
  package.json
  public/img/image.svg
  src/apis/image.ts
  src/components/MakeFlyer/AttachImage.tsx
  src/components/MakeFlyer/FillOutForm.tsx
  src/components/MakeFlyer/ImageUpload.tsx
  src/components/MakeFlyer/SelectCategory.tsx
  src/components/Street/FlyerList.tsx
  src/constants/apiUrls.ts
  src/hooks/useFetchImage.ts
  src/hooks/useGetImage.ts
  src/hooks/useMakeFlyer.ts
  src/hooks/usePreventLeave.ts
  src/interfaces/.empty
  src/interfaces/imageData.ts
  src/layouts/HeaderOff.tsx
  src/pages/MakeFlyer.tsx
  src/utils/convertURLtoFile.ts
  src/utils/imgToBase64.ts
Labels: enhancement, refactor

#27 feat: 메인 섹션 작업 및 코드 리팩토링
  index.html
  public/img/arrow.svg
  public/img/flyers.png
  public/img/note.png
  src/App.tsx
  src/components/Header.tsx
  src/components/Home/MainSection.tsx
  src/components/MakeFlyer/AttachImage.tsx
  src/components/MakeFlyer/FlyerForm.tsx
  src/components/MakeFlyer/ImageUpload.tsx
  src/components/MakeFlyer/SelectCategory.tsx
  src/components/MyInfo/Recent.tsx
  src/components/shared/Flyer.tsx
  src/hooks/useCountNumber.ts
  src/hooks/useFetchImage.ts
  src/hooks/useGetImage.ts
  src/hooks/useMakeFlyer.ts
  src/interfaces/flyerForm.ts
  src/pages/Home.tsx
  src/pages/MakeFlyer.tsx
  src/pages/MyInfo.tsx
Labels: enhancement, refactor

#28 feat: 전단지 작성 유효성 검사 제작
  package-lock.json
  package.json
  src/components/MakeFlyer/FlyerForm.tsx
  src/hooks/useMakeFlyer.ts
  src/hooks/usePreventLeave.ts
  src/interfaces/flyerForm.ts
  src/utils/validateFlyerForm.ts
Labels: enhancement

#29 feat: 메인페이지 퍼블리싱
  public/img/kakaoLogo.svg
  public/img/naverLogo.svg
  public/img/tornTape_1.png
  public/img/tornTape_1.svg
  public/img/tornTape_2.png
  public/img/tornTape_2.svg
  src/components/Home/LoginSection.tsx
  src/components/Home/MainSection.tsx
  src/components/Home/PromotionSection.tsx
  src/pages/Home.tsx
Labels: enhancement

#30 feat: 임시저장 기능 제작
  public/img/popular.png
  src/components/MakeFlyer/FlyerForm.tsx
  src/components/MakeFlyer/ImageUpload.tsx
  src/components/MakeFlyer/SelectCategory.tsx
  src/components/Street/FlyerList.tsx
  src/components/Street/PopularTags.tsx
  src/components/Street/Search.tsx
  src/components/Street/Sort.tsx
  src/constants/contacts.ts
  src/hooks/useMakeFlyer.ts
  src/interfaces/flyerForm.ts
  src/utils/validateFlyerForm.ts
Labels: enhancement, style

#37 refactor: 전단지 골목 레이아웃 수정
  README.md
  public/img/down.png
  public/img/up.png
  src/components/Header.tsx
  src/components/MakeFlyer/FlyerForm.tsx
  src/components/MakeFlyer/ImageUpload.tsx
  src/components/Street/Category.tsx
  src/components/Street/PopularTags.tsx
  src/components/Street/Sort.tsx
  src/hooks/useMakeFlyer.ts
  src/pages/FlyerStreet.tsx
Labels: refactor, style

#38 feat: 골목길 상세페이지 및 작성페이지(모바일)
  public/img/chat.svg
  public/img/close.svg
  public/img/mail.svg
  public/img/paperPlane.svg
  public/img/tornTape_1.png
  public/img/tornTape_2.png
  src/components/FlyerDetail/Comment.tsx
  src/components/FlyerDetail/Comments.tsx
  src/components/Home/PromotionSection.tsx
  src/components/MakeFlyer/Categorys.tsx
  src/components/MakeFlyer/FlyerForm.tsx
  src/components/MakeFlyer/ImageUpload.tsx
  src/components/MakeFlyer/SelectCategory.tsx
  src/interfaces/flyerForm.ts
  src/pages/FlyerDetail.tsx
  src/pages/MakeFlyer.tsx
  src/styles/GlobalStyle.tsx
Labels: enhancement

#39 feat: 메인 페이지 모바일 제작
  public/img/mainBgMob.png
  src/components/Home/LoginSection.tsx
  src/components/Home/MainSection.tsx
  src/components/Home/MovingText.tsx
  src/components/Home/PromotionSection.tsx
  src/components/shared/Flyer.tsx
Labels: enhancement

#41 feat: 내 정보 페이지 리디자인 및 골목길 태그 수정
  public/img/logo.svg
  public/img/write.svg
  src/components/Header.tsx
  src/components/Home/MainSection.tsx
  src/components/Home/PromotionSection.tsx
  src/components/MyInfo/Menus.tsx
  src/components/MyInfo/Profile.tsx
  src/components/MyInfo/Recent.tsx
  src/components/Street/PopularTags.tsx
  src/components/Street/Sort.tsx
  src/components/shared/Select.tsx
  src/constants/routes.ts
  src/hooks/useGetParams.ts
  src/hooks/useSearch.ts
  src/pages/MyInfo.tsx
Labels: enhancement, refactor, style
