Repository DO-youhave/Frontend, pull requests merged in 2023-03, with the labels that each got.

#42 refactor: 전단지 상세페이지 완성
  src/components/FlyerDetail/Comment.tsx
  src/components/FlyerDetail/Comments.tsx
  src/components/shared/.empty
  src/pages/FlyerDetail.tsx
Labels: refactor, style

#43 feat: 마이페이지 모바일 퍼블리싱 및 반응형 스타일 추가
  public/img/note.png
  public/img/profile.svg
  public/img/writeW.svg
  src/components/Header.tsx
  src/components/MyInfo/Menus.tsx
  src/components/MyInfo/MobileMenus.tsx
  src/components/MyInfo/Profile.tsx
  src/components/MyInfo/Recent.tsx
  src/components/Street/FlyerList.tsx
  src/components/Street/PopularTags.tsx
  src/pages/FlyerStreet.tsx
  src/pages/MyInfo.tsx
Labels: enhancement, refactor

#44 feat: 전단지 상세페이지 모바일 제작
  public/img/detailBack.png
  src/components/FlyerDetail/Comment.tsx
  src/components/FlyerDetail/Comments.tsx
  src/components/Home/LoginSection.tsx
  src/components/Home/MainSection.tsx
  src/components/Home/PromotionSection.tsx
  src/components/shared/Flyer.tsx
  src/constants/categorys.ts
  src/pages/FlyerDetail.tsx
Labels: refactor, style

#45 feat: API 적용 전 URL 및 미들웨어 구성 작업
  src/apis/handleRequest.ts
  src/apis/handleResponse.ts
  src/apis/image.ts
  src/apis/instance.ts
  src/constants/apiUrls.ts
  src/constants/auth.ts
Labels: enhancement, refactor

#47 feat: 로그인 API 틀 생성 및 고유값 셋팅 작업
  src/apis/Auth.ts
  src/components/Home/LoginSection.tsx
  src/components/Home/MainSection.tsx
  src/components/shared/OAuthButton.tsx
  src/constants/auth.ts
  src/constants/routes.ts
  src/interfaces/auth.ts
Labels: enhancement, refactor

#48 feat: 로그인 api 연동
  src/App.tsx
  src/apis/Auth.ts
  src/apis/Main.ts
  src/components/Home/MainSection.tsx
  src/components/Home/PromotionSection.tsx
  src/constants/categorys.ts
  src/constants/routes.ts
  src/hooks/useCountNumber.ts
  src/interfaces/main.ts
  src/pages/Redirect.tsx
Labels: enhancement, refactor

#53 fix: useCountNumber 커스텀 훅 버그 수정
  src/apis/Main.ts
  src/components/Home/MainSection.tsx
  src/hooks/useCountNumber.ts
  src/hooks/useGetCount.tsx
Labels: bug

#55 feat: 로그인 여부로 헤더 및 컴포넌트 변경
  src/components/Header.tsx
  src/components/Home/MainSection.tsx
  src/pages/Home.tsx
Labels: enhancement

#56 feat: 전단지 골목 전단지 리스트 API 연동
  package-lock.json
  package.json
  src/App.tsx
  src/apis/Main.ts
  src/components/Home/MainSection.tsx
  src/components/Home/PromotionSection.tsx
  src/components/Street/Flyer.tsx
  src/components/Street/FlyerList.tsx
  src/components/Street/Sort.tsx
  src/constants/categorys.ts
  src/constants/routes.ts
  src/hooks/useGetFlyerList.tsx
  src/interfaces/main.ts
  src/main.tsx
  src/pages/Home.tsx
Labels: enhancement, refactor, chore

#57 feat: 전단지 상세페이지 상세 정보 api 연동
  public/img/street.svg
  public/img/write.svg
  src/apis/FlyerDetail.ts
  src/components/Header.tsx
  src/constants/apiUrls.ts
  src/hooks/useGetFlyerDetail.ts
  src/interfaces/flyerDetail.ts
  src/pages/FlyerDetail.tsx
  src/utils/timeForToday.ts
Labels: bug, enhancement, style

#63 feat: 상세페이지 댓글/답글 생성 api 연동
  public/img/thinking.png
  src/apis/Comments.ts
  src/components/FlyerDetail/Comment.tsx
  src/components/FlyerDetail/Comments.tsx
  src/hooks/useGetComments.ts
  src/hooks/useGetFlyerDetail.ts
  src/hooks/useWriteComments.ts
  src/hooks/useWriteReply.ts
  src/interfaces/comment.ts
  src/pages/FlyerDetail.tsx
Labels: enhancement, style

#64 feat: 댓글 삭제/수정 기능 제작
  src/apis/Comments.ts
  src/components/FlyerDetail/Comment.tsx
  src/components/FlyerDetail/Comments.tsx
  src/components/FlyerDetail/Reply.tsx
  src/hooks/useEditComment.ts
  src/hooks/useEditReply.ts
  src/hooks/useGetComments.ts
  src/hooks/useGetFlyerDetail.ts
  src/hooks/useRemoveComment.ts
  src/hooks/useRemoveReply.ts
  src/hooks/useWriteComments.ts
  src/interfaces/comment.ts
  src/pages/FlyerDetail.tsx
Labels: bug, enhancement

#65 feat: 댓글, 전단지 신고 기능, 북마크 기능, 전단지 삭제 기능 제작
  src/apis/Comments.ts
  src/apis/FlyerDetail.ts
  src/components/FlyerDetail/Comment.tsx
  src/components/FlyerDetail/Reply.tsx
  src/constants/apiUrls.ts
  src/constants/routes.ts
  src/hooks/useGetFlyerDetail.ts
  src/hooks/useRemoveFlyer.ts
  src/hooks/useWriteReply.ts
  src/pages/FlyerDetail.tsx
Labels: enhancement, style

#66 hotfix: 카카오 로그인 리다이렉트 URL 추가
  src/components/MyInfo/Profile.tsx
  src/components/Street/Sort.tsx
  src/pages/Redirect.tsx
Labels: bug

#68 feat: 전단지 골목 전단지 플립효과 제작, 로그인/회원가입 페이지 제작
  src/App.tsx
  src/components/Header.tsx
  src/components/Street/Flyer.tsx
  src/components/shared/Flyer.tsx
  src/components/shared/OAuthButton.tsx
  src/constants/routes.ts
  src/pages/Login.tsx
Labels: enhancement, refactor

#69 feat: 내정보-최근알림 및 전단지 수정 api 작성 및 연동
  src/apis/Flyer.ts
  src/apis/FlyerDetail.ts
  src/apis/User.ts
  src/components/MakeFlyer/FlyerForm.tsx
  src/components/MyInfo/Flyer.tsx
  src/components/MyInfo/Recent.tsx
  src/hooks/useFetchImage.ts
  src/hooks/useGetMyPost.ts
  src/hooks/useGetNotifications.ts
  src/hooks/useGetProfile.ts
  src/hooks/useMakeFlyer.ts
  src/interfaces/flyerDetail.ts
  src/interfaces/flyerForm.ts
  src/interfaces/user.ts
  src/pages/FlyerDetail.tsx
Labels: enhancement

#71 refactor: 세부적인 기능 제작, 로딩 추가
  src/components/Header.tsx
  src/components/Home/PromotionSection.tsx
  src/components/MakeFlyer/FlyerForm.tsx
  src/components/Street/FlyerList.tsx
  src/components/Street/Search.tsx
  src/components/shared/Loading.tsx
  src/constants/textExamples.ts
  src/hooks/useGetFlyerDetail.ts
  src/hooks/useMakeFlyer.ts
  src/hooks/useSearch.ts
  src/interfaces/flyerForm.ts
  src/pages/FlyerDetail.tsx
  src/pages/FlyerStreet.tsx
  src/pages/Redirect.tsx
Labels: enhancement, refactor

#70 feat: 마이페이지 - 내가쓴글, 내가쓴댓글 api 연동
  src/App.tsx
  src/apis/Auth.ts
  src/apis/User.ts
  src/components/MyInfo/Exit.tsx
  src/components/MyInfo/Logout.tsx
  src/components/MyInfo/Menus.tsx
  src/components/MyInfo/MyComment.tsx
  src/components/MyInfo/MyMarked.tsx
  src/components/MyInfo/MyPosting.tsx
  src/components/Street/Flyer.tsx
  src/components/Street/FlyerList.tsx
  src/hooks/useGetMarkedFlyer.ts
  src/hooks/useGetMyComment.ts
  src/hooks/useGetMyPost.ts
  src/interfaces/auth.ts
  src/interfaces/user.ts
  src/pages/MyInfo.tsx
Labels: enhancement

#72 fix/refactor: 로그아웃 버그 수정, 모바일 버전 전단지 간격 조정
  src/components/MyInfo/Logout.tsx
  src/components/Street/Flyer.tsx
  src/components/Street/FlyerList.tsx
  src/hooks/useGetFlyerList.tsx
Labels: bug, refactor, style

#73 style: 마이페이지 컨텐츠 디자인 통일 작업
  src/components/MyInfo/Exit.tsx
  src/components/MyInfo/MyComment.tsx
  src/components/MyInfo/MyMarked.tsx
  src/components/MyInfo/MyPosting.tsx
  src/components/MyInfo/Recent.tsx
  src/hooks/useMakeFlyer.ts
Labels: bug, style

#74 fix: 탈퇴 사유 기타 항목 input 추가
  public/img/pen.svg
  src/components/MyInfo/Exit.tsx
Labels: bug

#75 feat: 있어요 v1.0.0 배포
  public/img/pen.svg
  src/App.tsx
  src/apis/Auth.ts
  src/apis/Flyer.ts
  src/apis/FlyerDetail.ts
  src/apis/User.ts
  src/components/Header.tsx
  src/components/Home/PromotionSection.tsx
  src/components/MakeFlyer/FlyerForm.tsx
  src/components/MyInfo/Exit.tsx
  src/components/MyInfo/Flyer.tsx
  src/components/MyInfo/Logout.tsx
  src/components/MyInfo/Menus.tsx
  src/components/MyInfo/MyComment.tsx
  src/components/MyInfo/MyMarked.tsx
  src/components/MyInfo/MyPosting.tsx
  src/components/MyInfo/Recent.tsx
  src/components/Street/Flyer.tsx
  src/components/Street/FlyerList.tsx
  src/components/Street/Search.tsx
  src/components/shared/Flyer.tsx
  src/components/shared/Loading.tsx
  src/components/shared/OAuthButton.tsx
  src/constants/routes.ts
  src/constants/textExamples.ts
  src/hooks/useFetchImage.ts
  src/hooks/useGetFlyerDetail.ts
  src/hooks/useGetFlyerList.tsx
  src/hooks/useGetMarkedFlyer.ts
  src/hooks/useGetMyComment.ts
  src/hooks/useGetMyPost.ts
  src/hooks/useGetNotifications.ts
  src/hooks/useGetProfile.ts
  src/hooks/useMakeFlyer.ts
  src/hooks/useSearch.ts
  src/interfaces/auth.ts
  src/interfaces/flyerDetail.ts
  src/interfaces/flyerForm.ts
  src/interfaces/user.ts
  src/pages/FlyerDetail.tsx
  src/pages/FlyerStreet.tsx
  src/pages/Login.tsx
  src/pages/MyInfo.tsx
  src/pages/Redirect.tsx
Labels: enhancement
